Sonarqube integration
smartcontractkit/chainlink-cosmos pull request #339
Opened 2023-06-19 09:09 UTC by davidcauchi

2023-06-23 15:18 UTC, jmank88 submitted a review, later dismissed

2023-06-26 07:51 UTC, cfal submitted a review, later dismissed

2023-06-26 07:51 UTC, cfal commented on .github/workflows/gauntlet.yml
> +        if: always()
nit: no need for `if` if it's always? same below

2023-07-04 13:04 UTC, krebernisak commented on .github/workflows/golangci-lint.yml
> +          args: --timeout=5m0s --tests=false --out-format checkstyle:golangci-lint-report.xml
Why do we keep the golangci-lint here but remove it from Solana in this [PR](https://github.com/smartcontractkit/chainlink-solana/pull/506/files)?

2023-07-04 13:04 UTC, krebernisak commented on .github/workflows/relay.yml
> +        run: nix develop -c go test -v ./pkg/cosmos/... -race -count=10 -coverpkg=./... -coverprofile=race_coverage.txt
Declaring custom CI steps inside a workflow is deprecated.

Please move these actions to Makefile and trigger them with make - we want all relevant project actions in a single place.

2023-07-10 13:51 UTC, chudilka1 commented on .github/workflows/golangci-lint.yml
> +          args: --timeout=5m0s --tests=false --out-format checkstyle:golangci-lint-report.xml
Solana repo has the same config, please take a look [here](https://github.com/smartcontractkit/chainlink-solana/pull/506/files#diff-8c8835f2d3ac63273eb6b8a21e7f78bf1496eb82d29de54cae99b6282818699cR42)

2023-07-10 13:55 UTC, chudilka1 approved these changes

2023-07-10 13:55 UTC, chudilka1 commented on .github/workflows/gauntlet.yml
> +        if: always()
The previous step, if it fails, won't let this one get executed w/o `if always`; however, we still want to get the report no matter the results of the previous step.

2023-09-06 07:35 UTC, cfal submitted a review, later dismissed
lgtm, left a nit about name_is_regexp

2023-09-06 07:35 UTC, cfal commented on .github/workflows/sonar-scan.yml
> +          name_is_regexp: true
name isn't a regexp and this can be false, same below: https://github.com/dawidd6/action-download-artifact#usage

2023-09-06 12:02 UTC, smickovskid submitted a review, later dismissed

2023-09-06 12:05 UTC, smickovskid approved these changes, later dismissed

2023-09-11 11:01 UTC, chudilka1 requested changes

2023-09-11 11:01 UTC, chudilka1 commented on .github/workflows/sonar-scan.yml
> +      - name: Download gauntlet test reports
Subject to removal as the tests are aimed at Solana (contracts) not supported by Sonar.

2023-09-11 11:01 UTC, chudilka1 commented on .github/workflows/gauntlet.yml
> +      - name: Upload test coverage report
Upload artifact is a subject to removal () as the tests are aimed at Solana (contracts) not supported by Sonar.

2023-09-11 11:01 UTC, chudilka1 commented on .github/workflows/sonar-scan.yml
> +          name: go-test-results
These results are downloaded (see [here](https://github.com/smartcontractkit/chainlink-cosmos/actions/runs/6143363647/job/16667114504?pr=339#step:5:23)), but not uploaded see [here](https://github.com/smartcontractkit/chainlink-cosmos/actions/runs/6143363647/job/16667114504?pr=339#step:5:23). Most of the time it happens if the path to reports is found.

2023-09-13 05:29 UTC, smickovskid commented on .github/workflows/gauntlet.yml
> +      - name: Upload test coverage report
These are mainly for gauntlet so we are good, the contracts tests here are copied over from the contracts dir which is excluded so they won't be scanned

2023-09-13 05:29 UTC, smickovskid commented on .github/workflows/sonar-scan.yml
> +      - name: Download gauntlet test reports
These are mainly for gauntlet so we are good, the contracts tests here are copied over from the contracts dir which is excluded so they won't be scanned

2023-09-21 11:27 UTC, cfal reviewed
lgtm overall - left a small comment. also could we rebase merge/develop? should fix the integration tests failure

2023-09-21 11:27 UTC, cfal commented on .eslintrc.json
> +    "ignorePatterns": ["./packages-ts/test/**", "**/node_modules/**"],
there's no `packages-ts/test`, remove?

2023-09-22 06:50 UTC, smickovskid approved these changes

2023-09-22 06:50 UTC, merged